# Generated by Django 5.1 on 2024-08-12 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('sku', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='products/')),
                ('price', models.FloatField()),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produtos.brands')),
            ],
        ),
    ]
