# Generated by Django 5.1 on 2024-08-12 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produtos', '0002_remove_products_brand_delete_brands_delete_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('sku', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='products/')),
                ('price', models.FloatField()),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produtos.brands')),
            ],
        ),
    ]
